services:
  folio-worker:
    image: folio/worker
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  folio-debian:
    image: folio/desktop/debian
    build:
      dockerfile: Dockerfile.debian

