[package]
version = "1.4.1.0" # TODO: inherit package version
name = "Wakunguma.Folio-Budgetingapp"
display-name = "Folio - Budgeting app"
publisher = "CN=70A3CBD3-185D-4DDE-9F41-27073B2FE013"
publisher-name = "Wakunguma"
logo="icons/icon.png"
resources = ["icons/*"]

[application]
id = "Folio"
display-name = "Folio"
executable = "../../target/release/folio.exe"
description = "A free, privacy focused budgeting app."
