[package]
name = "folio-updater"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true